---
variables:
  main: "./main.go"
  binary_name: "derocli"
  description: "a cli tool to fetch information from a dero rpc node"
  github_url: "github.com/stratumfarm/derocli"
  maintainer: "stratumfarm <pool@stratum.farm>"
  license: "MIT"
  homepage: "https://stratum.farm"
  aur_package: |-
      # bin
      install -Dm755 "./derocli" "${pkgdir}/usr/bin/derocli"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/derocli/LICENSE"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/derocli.bash" "${pkgdir}/usr/share/bash-completion/completions/derocli"
      install -Dm644 "./completions/derocli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_derocli"
      install -Dm644 "./completions/derocli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/derocli.fish"
      # man pages
      install -Dm644 "./manpages/derocli.1.gz" "${pkgdir}/usr/share/man/man1/derocli.1.gz"

before:
  hooks:
    - go mod tidy

builds:
  - 
    id: default
    env:
      - CGO_ENABLED=0
    main: '{{ .Var.main }}'
    binary: '{{ .Var.binary_name }}'
    ldflags: -s -w -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Version={{ .Version }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Commit={{ .Commit }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Date={{ .Date }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.BuiltBy=goreleaser
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"
    hooks:
      post: upx -9 "{{ .Path }}"
  - 
    id: bsd
    env:
      - CGO_ENABLED=0
    main: '{{ .Var.main }}'
    binary: '{{ with .Var.binary_name }}{{ . }}{{ else }}{{ .ProjectName }}{{ end }}'
    ldflags: -s -w -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Version={{ .Version }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Commit={{ .Commit }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.Date={{ .Date }} -X github.com/stratumfarm/{{ .Var.binary_name }}/internal/version.BuiltBy=goreleas
    flags: 
      - -trimpath
    goos:
      - freebsd
    goarch:
      - amd64
      - "386"

archives:
  - 
    name_template: "{{ .Var.binary_name }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    builds:
      - default
      - bsd
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - manpages/
      - completions

checksum:
  name_template: 'checksums.txt'

nfpms:
  - 
    file_name_template: "{{ .Var.binary_name }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    vendor: stratumfarm
    homepage: '{{ .Var.homepage }}'
    maintainer: '{{ .Var.maintainer }}'
    description: '{{ .Var.description }}'
    license: '{{ .Var.license }}'
    formats:
      - apk
      - deb
      - rpm

aurs:
  -
    name: '{{ .Var.binary_name }}-bin'
    homepage: '{{ .Var.homepage }}'
    description: '{{ .Var.description }}'
    maintainers:
      - '{{ .Var.maintainer }}'
    license: '{{ .Var.license }}'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/{{ .Var.binary_name }}-bin.git'
    package: '{{ .Var.aur_package }}'


source:
  enabled: true

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Others
      order: 999
